#################################################
# Base configuration
#################################################



#################################################
# Platforms to test
#################################################


include:
  - '.gitlab-ci-files/job-android.yml'
  - '.gitlab-ci-files/job-uitests.yml'
  - '.gitlab-ci-files/job-upload.yml'


stages:
 - build
 - uitests
 - deploy
