#################################################
# Base configuration
#################################################



#################################################
# Platforms to test
#################################################


include:
  - '.gitlab-ci-files/job-android.yml'
  - '.gitlab-ci-files/job-upload.yml'
  - '.gitlab-ci-files/job-uitests.yml'


stages:
  - build
  - deploy
  - uitests
