#dependencies:
  #install 'Java SE Development Kit 11' https://www.oracle.com/ca-en/java/technologies/javase/jdk11-archive-downloads.html
  #install 'Android Studio' https://developer.android.com/studio
  #install 'Android SDK Build-Tools', 'Android SDK Command-line Tools', 'Android Emulator', 'Android SDK Platform-Tools' from :
      #Android Studio > Tools > SDK Manager > SDK Tools
      #or Android Studio > Preferences > Appearence & Behavior > System Settings > Android SDK > SDK Tools

variables:
  android_api: "33" #android 13
  emulator_type: "apis" #atd for api < 30 more efficient
  system_architecture: "arm64-v8a" #x86_64 or x86 for Intels
  android_system_image: "system-images;android-$android_api;google_$emulator_type;$system_architecture" #'sdkmanager --list | grep system-images' to have all existing configs
  emulator_device: "pixel_6"
  emulator_name: "$emulator_device-api_$android_api-google_$emulator_type-arch_$system_architecture"


job-android-uitests:

  stage: uitests
  tags: [ "macmini-m1-bis-xcode13" ]

  dependencies:
    - job-android

  before_script:
    - git submodule update --init --recursive
    - ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "$android_system_image" > emulatorSystemImageInstallation.log
    - echo no | ${ANDROID_HOME}/cmdline-tools/latest/bin/avdmanager --verbose create avd --force --name $emulator_name --package $android_system_image --tag google_$emulator_type --abi $system_architecture --device $emulator_device > emulatorCreation.log
    - ${ANDROID_HOME}/platform-tools/adb start-server
    - ${ANDROID_HOME}/emulator/emulator -avd $emulator_name &
    - .gitlab-ci-files/wait-for-android-emulator

  script:
    - ./gradlew -Pandroid.testInstrumentationRunnerArguments.class=org.linphone.testsuites.CallTestSuite -PscreportAutoClose=true connectedAndroidTest
    - ${ANDROID_HOME}/platform-tools/adb -s emulator-5554 emu kill
    - ${ANDROID_HOME}/platform-tools/adb -s emulator-5554 emu kill
    - ${ANDROID_HOME}/platform-tools/adb kill-server

  after_script:
    - mkdir results && mv app/build/reports/androidTests/connected/* results
    - python3 .gitlab-ci-files/html2xml-report.py -p results
    
  artifacts:
    paths:
      - results/*
    when: always
    reports:
      junit:
        - results/*.xml
    expire_in: 4 week
