#dependencies:
  #install 'Android SDK Command-line Tools' from Android Studio > Tools > SDK Manager > SDK Tools > Android SDK Command-line Tools

variables:
  EMULATOR_PATH: /Users/quentin/Library/Android/sdk/emulator/
  CMD_LINE_PATH: /Users/quentin/Library/Android/sdk/cmdline-tools/latest/bin/
  android_api: "33" #android 13
  emulator_type: apis #atd for api < 30 more efficient
  system_architecture: x86_64 #arm64-v8a or x86 for Intels
  android_system_image: system-images;android-$android_api;google_$emulator_type;$system_architecture
  emulator_device: pixel_6
  emulator_name: $emulator_device-api_$android_api-google_$emulator_type-arch_$system_architecture


job-android-uitests:

  stage: uitests
  tags: [ "macmini-m1-bis-xcode13" ]

  dependencies:
    - job-android

  before_script:
    - echo $PATH
    - ${CMD_LINE_PATH}sdkmanager --install "$android_system_image" > emulatorSystemImageInstallation.log
    - echo $android_system_image
    - echo no | ${CMD_LINE_PATH}avdmanager --verbose create avd --force --name $emulator_name --package $android_system_image --tag google_$emulator_type --abi $system_architecture --device $emulator_device > emulatorCreation.log
    - adb start-server
    - ${EMULATOR_PATH}emulator -avd $emulator_name &
    - wait-for-android-emulator
    - adb shell input keyevent 82

  script:
  - ./gradlew -Pandroid.testInstrumentationRunnerArguments.class=org.linphone.call.OutgoingCallUITests -PscreportAutoClose=true connectedAndroidTest

  after_script:
    - adb -s emulator-5554 emu kill
    - adb -s emulator-5554 emu kill
    - adb kill-server
