#dependencies:
  #install 'Java SE Development Kit 11' https://www.oracle.com/ca-en/java/technologies/javase/jdk11-archive-downloads.html
  #install 'Android Studio' https://developer.android.com/studio
  #install 'Android SDK Build-Tools', 'Android SDK Command-line Tools', 'Android Emulator', 'Android SDK Platform-Tools' from :
      #Android Studio > Tools > SDK Manager > SDK Tools
      #or Android Studio > Preferences > Appearence & Behavior > System Settings > Android SDK > SDK Tools

variables:
  android_api: "33" #android 13
  emulator_type: "apis" #atd for api < 30 more efficient
  system_architecture: "arm64-v8a" #x86_64 or x86 for Intels
  android_system_image: "system-images;android-$android_api;google_$emulator_type;$system_architecture" # 'sdkmanager --list | grep system-images' to have all existing configs
  emulator_device: "pixel_6"
  emulator_name: "$emulator_device-api_$android_api-google_$emulator_type-arch_$system_architecture"
  emulator_adb_port: "5556" # max recommended 5586


job-android-uitests:

  stage: uitests
  tags: [ "macos-xcode13" ]

  dependencies:
    - job-android

  before_script:
    - git submodule update --init --recursive
    - mkdir logs && mkdir reports && mkdir apks

    #define adb tcp port
    - RUNNING_DEVICES=$(${ANDROID_HOME}/platform-tools/adb devices)
    - while [[ $RUNNING_DEVICES  == *$emulator_adb_port* ]]; do; emulator_adb_port=$(($emulator_adb_port + 2)); done
    - if [ $emulator_adb_port -gt 5586]; then; echo "|warning| the 15 recommended ports are already used by other emulators. ADB may not function properly for this emulator"; fi
    - emulator_name=$emulator_name-$emulator_adb_port

    #install emulator system-image and create it
    - ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "$android_system_image" > logs/emulatorSystemImageInstallation.log
    - echo no | ${ANDROID_HOME}/cmdline-tools/latest/bin/avdmanager --verbose create avd --force --name $emulator_name --package $android_system_image --tag google_$emulator_type --abi $system_architecture --device $emulator_device > logs/emulatorCreation.log

    #launch emulator
    - ${ANDROID_HOME}/platform-tools/adb start-server
    - ${ANDROID_HOME}/emulator/emulator -avd $emulator_name -port $emulator_adb_port &
    - .gitlab-ci-files/wait-for-android-emulator

    - ${ANDROID_HOME}/platform-tools/adb logcat -d > logs/logcats.log

  script:
    - set +e

    #launch uitest suite
    - ./gradlew -Pandroid.testInstrumentationRunnerArguments.class=org.linphone.testsuites.CallTestSuite -PscreportWindowed=false connectedAndroidTest --continue
    - export BUILD_RESULT=$?

    #kill emultator (twice in case a confirm dialog popup appears)
    - ${ANDROID_HOME}/platform-tools/adb -s emulator-5554 emu kill
    - ${ANDROID_HOME}/platform-tools/adb -s emulator-5554 emu kill 
    - ${ANDROID_HOME}/platform-tools/adb kill-server

    - if [$BUILD_RESULT -eq 0] || [ ! -d app/build/reports/androidTests/connected/failures ]; then exit 0; else exit 1; fi

  after_script:
    #artifacts preparation
    - mv app/build/reports/androidTests/connected/* reports
    - mv app/build/outputs/apk/debug/linphone-android-debug-*.apk ./apks/debug
    - mv app/build/outputs/apk/release/linphone-android-release-*.apk ./apks/release
    - .gitlab-ci-files/html2xml-report -p reports
    
  artifacts:
    paths:
      - reports/*
      - logs/*
      - apks/debug/linphone-android-debug-*.apk
      - apks/release/linphone-android-release-*.apk
    when: always
    reports:
      junit:
        - reports/*.xml
    expire_in: 4 week
