job-android:

  stage: build
  tags: [ "docker-android" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-android/bc-dev-android:20220609_android_33

  before_script:
    - if ! [ -z ${SCP_PRIVATE_KEY+x} ]; then eval $(ssh-agent -s); fi
    - if ! [ -z ${SCP_PRIVATE_KEY+x} ]; then echo "$SCP_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null; fi
    - echo "$ANDROID_SETTINGS_GRADLE" > settings.gradle

  script:
    - sdkmanager
    - scp -oStrictHostKeyChecking=no $DEPLOY_SERVER:$ANDROID_KEYSTORE_PATH app/
    - scp -oStrictHostKeyChecking=no $DEPLOY_SERVER:$ANDROID_GOOGLE_SERVICES_PATH app/
    - echo storePassword=$ANDROID_KEYSTORE_PASSWORD > keystore.properties
    - echo keyPassword=$ANDROID_KEYSTORE_KEY_PASSWORD >> keystore.properties
    - echo keyAlias=$ANDROID_KEYSTORE_KEY_ALIAS >> keystore.properties
    - echo storeFile=$ANDROID_KEYSTORE_FILE >> keystore.properties
    - ./gradlew app:dependencies | grep org.linphone
    - ./gradlew assembleDebug
    - ./gradlew assembleRelease
    
  after_script:
    - ln -s ./app/build/outputs/apk/debug/linphone-android-debug-*.apk ./apk/debug
    - ln -s ./app/build/outputs/apk/release/linphone-android-release-*.apk ./apk/release

  artifacts:
    paths:
      - ./app/build
      - ./apk/debug
      - ./apk/release
    when: always
    expire_in: 2 hour


.scheduled-job-android:
  extends: job-android
  only:
    - schedules
